AWSTemplateFormatVersion: 2010-09-09
Description: |
  This project converts numbers into Roman numerals.

Resources:
  MerveInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-04cb4ca688797756f
      InstanceType: t2.micro
      KeyName: firstkey 
      SecurityGroups:
        - !Ref MerveInstanceSG
      Tags:
        - Key: Name
          Value: MerveEriskin
        - Key: Project
          Value: Roman-Numerals-Project
      UserData:
        Fn::Base64: !Sub |
          #! /bin/bash
          sudo dnf update -y
          sudo dnf install python -y
          sudo dnf install pip -y
          sudo pip install Flask
          wget -P templates https://raw.githubusercontent.com/emrverskn/Roman-Numerals-Converter/main/templates/index.html
          wget -P templates https://raw.githubusercontent.com/emrverskn/Roman-Numerals-Converter/main/templates/result.html
          wget https://raw.githubusercontent.com/emrverskn/Roman-Numerals-Converter/main/roman-numerals-converter-app.py
          sudo python3 roman-numerals-converter-app.py


  MerveInstanceSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allows SSH
      GroupName: "Roman-Numerals-ProjectSG"
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0